from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
BANK_DIR = ROOT / "content" / "questions" / "bank"
OUT_PATH = ROOT / "supabase" / "migrations" / "007_questions_seed.sql"


def sql_text(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_nullable_text(value: str | None) -> str:
    if value is None:
        return "null"
    return sql_text(value)


def sql_nullable_int(value: int | None) -> str:
    if value is None:
        return "null"
    return str(value)


def sql_jsonb(value: Any) -> str:
    if value is None:
        return "null"
    return sql_text(json.dumps(value, ensure_ascii=False)) + "::jsonb"


def sql_bool(value: bool) -> str:
    return "true" if value else "false"


def load_bank_questions() -> list[dict[str, Any]]:
    questions: list[dict[str, Any]] = []
    for path in sorted(BANK_DIR.rglob("*.json")):
        items = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(items, list):
            continue
        questions.extend(items)
    return questions


def render_row(question: dict[str, Any]) -> str:
    return "(" + ", ".join(
        [
            sql_text(question["id"]),
            sql_text(question["chapter_id"]),
            sql_text(question["qtype"]),
            sql_text(question["stem"]),
            sql_jsonb(question.get("options")),
            sql_text(question.get("answer", "")),
            sql_text(question.get("explanation", "")),
            sql_nullable_text(question.get("source_file")),
            sql_nullable_int(question.get("source_page")),
            sql_bool(bool(question.get("needs_review", False))),
            str(int(question.get("sort_order", 0))),
            "null",
        ]
    ) + ")"


def main() -> None:
    questions = load_bank_questions()
    rows = ",\n  ".join(render_row(question) for question in questions)
    sql = (
        f"-- generated by scripts/build_question_seed.py\n"
        f"-- question_count: {len(questions)}\n\n"
        "insert into public.questions (\n"
        "  id,\n"
        "  chapter_id,\n"
        "  qtype,\n"
        "  stem,\n"
        "  options,\n"
        "  answer,\n"
        "  explanation,\n"
        "  source_file,\n"
        "  source_page,\n"
        "  needs_review,\n"
        "  sort_order,\n"
        "  user_id\n"
        ")\nvalues\n  "
        + rows
        + "\non conflict (id) do update set\n"
        "  chapter_id = excluded.chapter_id,\n"
        "  qtype = excluded.qtype,\n"
        "  stem = excluded.stem,\n"
        "  options = excluded.options,\n"
        "  answer = excluded.answer,\n"
        "  explanation = excluded.explanation,\n"
        "  source_file = excluded.source_file,\n"
        "  source_page = excluded.source_page,\n"
        "  needs_review = excluded.needs_review,\n"
        "  sort_order = excluded.sort_order,\n"
        "  user_id = excluded.user_id\n"
        "where public.questions.needs_review is true;\n"
    )
    OUT_PATH.write_text(sql, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT).as_posix()}")
    print(f"question_count={len(questions)}")


if __name__ == "__main__":
    main()
